const ts=require('../frontend/node_modules/typescript');
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const dates={};
vm.runInNewContext(ts.transpileModule(fs.readFileSync('frontend/src/dates.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText,{exports:dates,Date});
const exportsObject={};
const source=ts.transpileModule(fs.readFileSync('frontend/src/main.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,experimentalDecorators:true}}).outputText;
vm.runInNewContext(source,{exports:exportsObject,require:(name)=>name==='@angular/core'?{Component:()=>()=>{},HostListener:()=>()=>{}}:name==='@angular/platform-browser'?{bootstrapApplication:()=>Promise.resolve()}:name==='./language'?{readLanguagePreference:()=> 'en',detectLanguage:()=> 'en',translate:text=>text}:name==='./dates'?dates:{},document:{cookie:''},window:{scrollTo(){}},console,Date});
const app=new exportsObject.App();
app.mobileToolsOpen=true;app.navigateTool('studio');
assert.equal(app.page,'templates','No selected documents should return to the chooser');
assert.equal(app.mobileToolsOpen,false);
app.docs.find(doc=>doc.id==='tenancy').selected=true;app.d.tenant_name='Unsaved tenant';app.step=3;
app.mobileToolsOpen=true;app.navigateTool('income');assert.equal(app.page,'income');assert.equal(app.mobileToolsOpen,false);
app.navigateTool('studio');assert.equal(app.page,'studio');assert.equal(app.step,3);assert.equal(app.d.tenant_name,'Unsaved tenant');
app.mobileToolsOpen=true;app.navigateTool('settings');assert.equal(app.settings,true);assert.equal(app.mobileToolsOpen,false);
app.settings=false;app.reset();
console.log('Team Tools navigation, chooser fallback and unsaved form preservation passed');
const form={reportValidity:()=>true};
app.d.start_date='2025-10-10';app.chooseTerm(6);
assert.equal(app.d.end_date,'2026-05-01');
app.d.start_date='2026-04-10';app.updateExpiry();
assert.equal(app.d.end_date,'2026-11-01');
app.chooseTerm(12);assert.equal(app.d.end_date,'2027-05-01');
for(const [id,path] of [['offer',[0,1,3]],['tenancy',[0,1,3]],['move_in',[0,2,3]],['rules',[0,3]]]){
  app.startDocuments(id);assert.equal(JSON.stringify(app.activeSteps),JSON.stringify(path));
  app.d.end_date='2027-10-01';
  for(const expected of path.slice(1)){app.next(form);assert.equal(app.step,expected);}
  app.back();assert.equal(app.step,path[path.length-2]);
}
app.docs.forEach(doc=>doc.selected=true);assert.equal(JSON.stringify(app.activeSteps),'[0,1,4,2,3]');
app.startDocuments('offer');app.d.tenant_name='Test';app.d.tenant_id='TEST';app.d.property='';assert.equal(app.validate(['offer']),false);
app.startDocuments('move_in');assert.equal(app.validate(['move_in']),true);
app.startDocuments('rules');app.d.tenant_name='';app.d.tenant_id='';assert.equal(app.validate(['rules']),true);
console.log('Document paths, back navigation, bundles and validation passed');
app.d.reference='TEST';app.d.aircon=true;app.d.aircon_kwh=65;
assert.equal(app.documentDetails(['tenancy']).aircon_kwh,65);
assert.equal(app.documentDetails(['offer']).aircon_kwh,undefined);
app.d.aircon=false;assert.equal(app.documentDetails(['tenancy']).aircon_kwh,undefined);
app.d.aircon=true;app.d.aircon_kwh=null;assert.equal(app.validate(['tenancy']),false);
app.reset();assert.equal(app.d.aircon_kwh,40);
console.log('AC allowance payload, validation and reset checks passed');

app.d.reference='TEST-PRORATE';app.d.start_date='2026-10-17';app.d.rent=1000;app.d.advance_rent=999;
assert.equal(app.proratedRent,483.87);
assert.equal(app.documentDetails(['offer']).advance_rent,483.87);
assert.equal(app.total,483.87);
app.d.start_date='2026-10-31';assert.equal(app.proratedRent,32.26);
app.d.rent=3100;assert.equal(app.proratedRent,100);
app.d.rent=null;assert.equal(app.proratedRent,null);
console.log('Automatic rental, stale draft value, payload and total checks passed');

app.reset();app.d.property='16-03';app.startDocuments('carpark');
assert.equal(JSON.stringify(app.activeSteps),'[0,4,3]');
app.go(4);assert.equal(app.d.carpark_lot,'16-03');assert.equal(app.d.carpark_rent,300);
app.d.carpark_lot='CP-7';app.go(0);app.go(4);assert.equal(app.d.carpark_lot,'CP-7');
app.d.carpark_start_date='2026-10-17';app.chooseCarparkTerm(6);
assert.equal(app.d.carpark_end_date,'2027-04-16');assert.equal(app.carparkEarnest,145.16);
app.d.rent=1200;app.d.start_date='2026-10-01';
assert.equal(app.carparkEarnest,145.16);
const cp=app.documentDetails(['carpark']);assert.equal(cp.carpark_earnest_deposit,145.16);assert.equal(cp.rent,undefined);assert.equal(cp.start_date,undefined);
assert.equal(app.documentDetails(['tenancy']).carpark_rent,undefined);
app.reset();app.startDocuments('carpark');app.go(4);assert.equal(app.d.carpark_lot,'');
console.log('Car park workflow, default lot, separate dates/payments and payload checks passed');

app.reset();app.startDocuments('tenancy');
assert.equal(app.d.tenancy_type,'new');
assert.equal(app.d.parking,null);
assert(app.visibleMoneyFields.some(f=>f.key==='parking'));
app.d.parking=250;app.d.carpark_rent=300;app.d.tenancy_type='renewal';
assert.equal(app.documentDetails(['tenancy']).parking,250);
assert.equal(app.documentDetails(['tenancy']).tenancy_type,'renewal');
assert.equal(app.documentDetails(['carpark']).carpark_rent,300);
assert.equal(app.documentDetails(['carpark']).tenancy_type,undefined);
app.d.aircon=false;assert(app.visibleMoneyFields.some(f=>f.key==='parking'));
app.startDocuments('offer');assert(!app.visibleMoneyFields.some(f=>f.key==='parking'));
console.log('TA parking, tenancy type and independent car park inputs passed');

(async()=>{
  app.reset();
  assert.equal(app.inventory.length,20);
  assert(app.inventory.some(i=>i.name==='Study table'));
  assert(app.inventory.some(i=>i.name==='Lamp'));
  const inventory=app.inventory.filter(i=>i.name!=='Lamp').map(i=>i.name==='Study table'?{...i,name:'Makeup table',quantity:2,condition:'Fair',remarks:'Existing desk'}:i);
  const draft={version:1,details:{...app.d,inventory,makeup_table_drawer:'with'},documents:['move_in']};
  const input={files:[{size:1000,text:async()=>JSON.stringify(draft)}],value:'draft.json'};
  await app.loadDraft({target:input});
  assert.equal(app.error,'');
  const table=app.inventory.find(i=>i.name==='Study table');
  assert.equal(table.quantity,2);assert.equal(table.remarks,'Existing desk');
  assert.equal(app.inventory.find(i=>i.name==='Lamp').quantity,1);
  assert.equal(app.inventory.length,20);
  assert(!('makeup_table_drawer' in app.documentDetails(['move_in'])));
  assert(!fs.readFileSync('frontend/src/app.html','utf8').includes('makeup_table_drawer'));
  console.log('Study table, Lamp, obsolete drawer removal and older draft migration passed');
})().catch(error=>{console.error(error);process.exitCode=1;});
